language: php

php:
  - 7.1
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.2.*

before_script:
  - travis_retry composer self-update

install:
   - composer require symfony/framework-bundle:${SYMFONY_VERSION}


script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)
